### ISSUE TITLE
Robustness of 'core.py' script. 

### ISSUE THREAD

**Issue by Valeriy-Burlaka** [medsleuthinc/aws-whitelabel#4]
I've observed various failures in "core.py" script during deployment of "s4-client".
Although, when re-run the build step, a failure usually goes away (e.g., conditions change, such as needed stack finishes to create, etc.), the script may benefit from a more close review and some re-factoring to make it more reliable and/or fail more gracefully.
Examples:
![screenshot 2018-12-10 19 00 57](https://user-images.githubusercontent.com/6002242/49755879-985a3c80-fcb9-11e8-95d2-ce20b6172539.png)

<img width="856" alt="screenshot 2018-12-07 13 53 15" src="https://user-images.githubusercontent.com/6002242/49755943-af992a00-fcb9-11e8-95e1-6c1bd92856e1.png"> (this is already addressed by #2 )

![screenshot 2018-12-07 14 49 34](https://user-images.githubusercontent.com/6002242/49756110-f0913e80-fcb9-11e8-8cc2-3f3d0f30eb54.png)
(It was my mistake to not include B2 frontend in my infra, but I don't think it should be a silent `KeyError` here)

etc.

**Comment by romaninsh** [comment]
this should be solved in infrastructure 2.1 now, where we introduce "wait" before triggering this script.

**Comment by ficcaglia** [comment]
B2-frontend should not be required for a b3 stack

**Comment by romaninsh** [comment]
I'm closing this issue. aws-whitelabel is not very pretty, but cleaning-up / refactoring would probably take some time / effort.
